apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: employee-management
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_db
